name       : discord
version    : 0.0.2
release    : 2
source     :
    - https://dl.discordapp.net/apps/linux/0.0.2/discord-0.0.2.tar.gz : dfc17ac6f683a45f896a4f881b900b2d46d74b0625cb661db1bfe39b33a06769
license    : Distributable
component  : network.im
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
replaces   :
    - discord-canary
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xcomposite)
    - pkgconfig(xi)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(x11)
rundeps    :
    - llvm
install    : |
    install -D -m 00644 discord.desktop $installdir/usr/share/applications/discord.desktop
    install -D -m 00644 discord.png $installdir/usr/share/pixmaps/discord.png

    # Binary
    install -D -m 00755 Discord $installdir/usr/share/discord/Discord
    install -D -d -m 0755 $installdir/usr/bin
    ln -sv ../share/discord/Discord $installdir/usr/bin/discord

    # Assets
    for i in *.pak *.dat *.bin; do
        install -m 00644 $i $installdir/usr/share/discord/.
    done

    # .so's
    for i in *.so; do
        install -m 00755 $i $installdir/usr/share/discord/.
    done

    # Asset dirs
    for i in locales resources; do
        cp -Ra $i $installdir/usr/share/discord/.
    done
