name       : discord
version    : 0.0.22
release    : 29
source     :
    - https://dl.discordapp.net/apps/linux/0.0.22/discord-0.0.22.tar.gz : 175c73771e049ba45e7fb1d37bd107ef0871e3d8857340c5a5a40a745aaeaba7
license    : Distributable
component  : network.im
homepage   : https://discord.com/
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
replaces   :
    - discord-canary
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xshmfence)
rundeps    :
    - llvm
    - opus
install    : |
    install -Dm00644 discord.desktop $installdir/usr/share/applications/discord.desktop
    install -Dm00644 discord.png $installdir/usr/share/pixmaps/discord.png

    # Binary
    install -Dm00755 Discord $installdir/usr/share/discord/Discord
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/discord/Discord $installdir/usr/bin/discord

    # Assets
    for i in *.pak *.dat *.bin *.png; do
        install -m00644 $i $installdir/usr/share/discord/.
    done

    # .so's
    for i in *.so; do
        install -m00755 $i $installdir/usr/share/discord/.
    done

    # Asset dirs
    for i in locales resources; do
        cp -Ra $i $installdir/usr/share/discord/.
    done
