name       : discord
version    : 0.0.11
release    : 17
source     :
    - https://dl.discordapp.net/apps/linux/0.0.11/discord-0.0.11.tar.gz : a474761d72ee3fb7fdd31aefc441fc5aa953a2f5dcbe8c30f14fbe105fe458e9
license    : Distributable
component  : network.im
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
replaces   :
    - discord-canary
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xfixes)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
rundeps    :
    - llvm
    - opus
install    : |
    install -D -m 00644 discord.desktop $installdir/usr/share/applications/discord.desktop
    install -D -m 00644 discord.png $installdir/usr/share/pixmaps/discord.png

    # Binary
    install -D -m 00755 Discord $installdir/usr/share/discord/Discord
    install -D -d -m 0755 $installdir/usr/bin
    ln -sv ../share/discord/Discord $installdir/usr/bin/discord

    # Assets
    for i in *.pak *.dat *.bin; do
        install -m 00644 $i $installdir/usr/share/discord/.
    done

    # .so's
    for i in *.so; do
        install -m 00755 $i $installdir/usr/share/discord/.
    done

    # Asset dirs
    for i in locales resources; do
        cp -Ra $i $installdir/usr/share/discord/.
    done
