name       : discord
version    : 0.0.30
release    : 41
source     :
    - https://dl.discordapp.net/apps/linux/0.0.29/discord-0.0.29.tar.gz : def8cebe4a8c0fba8a5f6cd151b2abc39807b44feff167c7e79eebb5a8162167
license    : Distributable
component  : network.im
homepage   : https://discord.com/
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
replaces   :
    - discord-canary
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xshmfence)
rundeps    :
    - llvm
    - libappindicator
    - opus
# strip and debug will prevent krisp noise supression from loading
strip      : no
debug      : no
install    : |
    install -Dm00644 $pkgfiles/discord.desktop $installdir/usr/share/applications/discord.desktop
    install -Dm00644 discord.png $installdir/usr/share/pixmaps/discord.png
    install -Dm00644 $pkgfiles/discord.appdata.xml $installdir/usr/share/metainfo/discord.appdata.xml

    # Binary
    install -Dm00755 Discord $installdir/usr/share/discord/Discord
    install -dm00755 $installdir/usr/bin
    ln -sv ../share/discord/Discord $installdir/usr/bin/discord

    # Assets
    for i in *.pak *.dat *.bin *.png; do
        install -m00644 $i $installdir/usr/share/discord/.
    done
    install -m00755 chrome_crashpad_handler $installdir/usr/share/discord/

    # .so's
    for i in *.so; do
        install -m00755 $i $installdir/usr/share/discord/.
    done

    # Asset dirs
    for i in locales resources; do
        cp -Ra $i $installdir/usr/share/discord/.
    done
